name: Run tests
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20.9.0

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npm test

      # Agregar un script post-test
      - name: Check test results
        run: |
          if npm test | grep -q "Test failed"; then
            echo "Al menos una prueba ha fallado. No se publicará el commit ni se realizará la actualización en el repositorio."
            exit 1
          fi

      # Solo continuar si todas las pruebas pasaron
      - name: Commit and Push
        if: success()
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Actualizar cambios"
          git push
