
name: Run tests
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20.9.0

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npm test

      # Agregar un script post-test
      - name: Check test results
        run: |
          if [ $? -ne 0 ]; then
            echo "Al menos una prueba ha fallado. No se publicará el commit."
            exit 1
          fi

